### ISSUE TITLE
MacOS Ventura 13.0

### ISSUE THREAD

**Issue by Han2Tong** [LimeVista/Hackintosh-H610-12490F-AX201#1]
楼主有没有试试MacOS Ventura 13.0能不能平滑升级呢

**Comment by LimeVista** [comment]
肯定是不能，下次我更新到了 13.0 会同步出来。

**Comment by LimeVista** [comment]
@Han2Tong 已经更新，你可以尝试下

**Comment by eeyyee** [comment]
> @Han2Tong 已经更新，你可以尝试下

老哥现在这个efi还支持蒙特罗吗
