### ISSUE TITLE
大佬有全套配置吗，最近想买个一样的

### ISSUE THREAD

**Issue by songxing10000** [LimeVista/Hackintosh-H610-12490F-AX201#17]

**Comment by LimeVista** [comment]
@songxing10000 基本写在介绍那里了，显卡建议是蓝宝石的，这个品牌兼容性一般，如果手里有 RX580 会更好，不过580是矿难之王。

**Comment by LimeVista** [comment]
最近买个一样的就没必要了吧，毕竟 M 系列已经成熟了。不过台式机的大内存还是爽，苹果的内存就是黄金价格。

**Comment by songxing10000** [comment]
我是14年就用白果至今，只是最近想换黑的，感觉性价比不行啊，大内存大SSD感觉很爽

**Comment by LimeVista** [comment]
> 我是14年就用白果至今，只是最近想换黑的，感觉性价比不行啊，大内存大SSD感觉很爽。主要想跟大佬全套一样，散热，机箱，电源的全都一样。另外显卡换了，是不是EFI得改啊

如果是 RX580 不用 RX590 不用，我实测。

**Comment by LimeVista** [comment]
> 我是14年就用白果至今，只是最近想换黑的，感觉性价比不行啊，大内存大SSD感觉很爽。主要想跟大佬全套一样，散热，机箱，电源的全都一样。另外显卡换了，是不是EFI得改啊

扇热和机箱没有要求。主要区别就是 CPU 主板 还有 显卡。其实主板占很大问题，我这块主板的不同 BIOS 也可能需要进行折腾。
