### ISSUE TITLE
铭瑄H610ITX 2LAN - i3 12100F - rx 560 -  AX211 可以使用

### ISSUE THREAD

**Issue by Arjen10** [LimeVista/Hackintosh-H610-12490F-AX201#19]
经过两天的折腾，整理下遇到的问题

## 卡EB问题（包括issues中也提到了这个问题）

```txt
#LEB.LD.LF|IN] 0 1<"<null string>”><”1”>
#IEB.8.SBSIS21 723512
#LEBIB:SHA1 <5ff7a493bd3c631683fa0d2730af039b85952466>
#LEB.WL.PWLFNV|!] Err(0xE)<- RT.Gy wake-fallure 7C436110-AB2A
#LEB.WL.DTI!] Err(OxE)<- EB.WL.PWLFNV
#IEB.WL.PWLFRTCINONE]
#LEB.WL.DTI!] Err(OxE)<- EB.WL.PWLFRTC
#[EB.LD .LKCIR.1]<"System\Library\KernelCollectionsiBootKernelE)
#LEB.LD.LKFS1-?] 0k(0)
#LEB.LD.LKCI-?1 0k(0)
#LEBIBST:REV11#LEBICSR:IN] 0x00000040#[EBICSR:0UT1 0x00000040
#LEB.BST.FBSI+]
#LEB.BST.FBSIADSZ] 0#IEB .BST.FBSIKSSZ] 0
#[EBISB:SBGMFNS1 j160ap.im4m
#[EB|RH:PF1 usristandalonel0s .dmg.root hash
#[EBIRH:MF]<"usristandalonelt0s.dmg.root hash.j160ap.im4m")
#LEB.LD.LFlIN] 0 1<"usrlistandalonel0s.dmg.root hash"><”0”
#LEB.LD .OFSIOPEN!1 Err(0xE)<"usriistandalonell0s.dmg.root hash”)
#LEB.RH.LRHIP!I Err(OxE)<- EB.LD.LF
#LEB.BST.FBS!!] Err(OxE)<- EB.RH.LRH
#LEBIL0G:DT1 2024-04-13T22:03:42
#[EBILOG:EXITBS:START1 2024-04-13T22:03:42
```

[参考远景解决方案](https://bbs.pcbeta.com/viewthread-1961581-1-1.html)

勾选 Config-booter-Quirks-SetupVirtualMap

## Sonoma 14.4验证

无法加载14.4，现目前使用14.2.1正常使用。没有研究为什么，应该是EFI不适配最新Macos导致。

## 总结

此EFI适配铭瑄H610系列应该问题不大。

1、USB端口也无需二次定制（我只用到了四个USB）。

2、蓝牙、Wi-Fi intel AX211 网卡（作者更新了最新上游最新kext），现目前驱动正常。

3、2.5G网口正常（我是升级版主板，多出的1G网口未做测试，我也不需要，只需要2.5G网口即可）。

感谢此仓库作者，以及大家的问题反馈和对应的解决方案。

**Comment by LimeVista** [comment]
14.4 预计这个月我会上传，看我懒不懒吧。哈哈哈

**Comment by LimeVista** [comment]
> 经过两天的折腾，整理下遇到的问题
> 
> ## 卡EB问题（包括issues中也提到了这个问题）
> ```
> #LEB.LD.LF|IN] 0 1<"<null string>”><”1”>
> #IEB.8.SBSIS21 723512
> #LEBIB:SHA1 <5ff7a493bd3c631683fa0d2730af039b85952466>
> #LEB.WL.PWLFNV|!] Err(0xE)<- RT.Gy wake-fallure 7C436110-AB2A
> #LEB.WL.DTI!] Err(OxE)<- EB.WL.PWLFNV
> #IEB.WL.PWLFRTCINONE]
> #LEB.WL.DTI!] Err(OxE)<- EB.WL.PWLFRTC
> #[EB.LD .LKCIR.1]<"System\Library\KernelCollectionsiBootKernelE)
> #LEB.LD.LKFS1-?] 0k(0)
> #LEB.LD.LKCI-?1 0k(0)
> #LEBIBST:REV11#LEBICSR:IN] 0x00000040#[EBICSR:0UT1 0x00000040
> #LEB.BST.FBSI+]
> #LEB.BST.FBSIADSZ] 0#IEB .BST.FBSIKSSZ] 0
> #[EBISB:SBGMFNS1 j160ap.im4m
> #[EB|RH:PF1 usristandalonel0s .dmg.root hash
> #[EBIRH:MF]<"usristandalonelt0s.dmg.root hash.j160ap.im4m")
> #LEB.LD.LFlIN] 0 1<"usrlistandalonel0s.dmg.root hash"><”0”
> #LEB.LD .OFSIOPEN!1 Err(0xE)<"usriistandalonell0s.dmg.root hash”)
> #LEB.RH.LRHIP!I Err(OxE)<- EB.LD.LF
> #LEB.BST.FBS!!] Err(OxE)<- EB.RH.LRH
> #LEBIL0G:DT1 2024-04-13T22:03:42
> #[EBILOG:EXITBS:START1 2024-04-13T22:03:42
> ```
> 
> [参考远景解决方案](https://bbs.pcbeta.com/viewthread-1961581-1-1.html)
> 
> 勾选 Config-booter-Quirks-SetupVirtualMap
> 
> ## Sonoma 14.4验证
> 无法加载14.4，现目前使用14.2.1正常使用。没有研究为什么，应该是EFI不适配最新Macos导致。
> 
> ## 总结
> 此EFI适配铭瑄H610系列应该问题不大。 1、USB端口也无需二次定制（我只用到了四个USB）。 2、蓝牙、Wi-Fi intel AX211 网卡作者更新了最新上游最新kext，现目前驱动正常。 3、2.5G网口正常（我是升级版主板，多出的1G网口未做测试，我也不需要，只需要2.5G网口即可）。
> 
> 感谢此仓库作者，以及大家的问题反馈和对应的解决方案。

我可能近一年没有重新安装，感谢你遇到问题一起分享，后续我会把 14.4 的分享出来，不过最近比较懒，还在测试中。

**Comment by Arjen10** [comment]
> > 经过两天的折腾，整理下遇到的问题
> > ## 卡EB问题（包括issues中也提到了这个问题）
> > ```
> > #LEB.LD.LF|IN] 0 1<"<null string>”><”1”>
> > #IEB.8.SBSIS21 723512
> > #LEBIB:SHA1 <5ff7a493bd3c631683fa0d2730af039b85952466>
> > #LEB.WL.PWLFNV|!] Err(0xE)<- RT.Gy wake-fallure 7C436110-AB2A
> > #LEB.WL.DTI!] Err(OxE)<- EB.WL.PWLFNV
> > #IEB.WL.PWLFRTCINONE]
> > #LEB.WL.DTI!] Err(OxE)<- EB.WL.PWLFRTC
> > #[EB.LD .LKCIR.1]<"System\Library\KernelCollectionsiBootKernelE)
> > #LEB.LD.LKFS1-?] 0k(0)
> > #LEB.LD.LKCI-?1 0k(0)
> > #LEBIBST:REV11#LEBICSR:IN] 0x00000040#[EBICSR:0UT1 0x00000040
> > #LEB.BST.FBSI+]
> > #LEB.BST.FBSIADSZ] 0#IEB .BST.FBSIKSSZ] 0
> > #[EBISB:SBGMFNS1 j160ap.im4m
> > #[EB|RH:PF1 usristandalonel0s .dmg.root hash
> > #[EBIRH:MF]<"usristandalonelt0s.dmg.root hash.j160ap.im4m")
> > #LEB.LD.LFlIN] 0 1<"usrlistandalonel0s.dmg.root hash"><”0”
> > #LEB.LD .OFSIOPEN!1 Err(0xE)<"usriistandalonell0s.dmg.root hash”)
> > #LEB.RH.LRHIP!I Err(OxE)<- EB.LD.LF
> > #LEB.BST.FBS!!] Err(OxE)<- EB.RH.LRH
> > #LEBIL0G:DT1 2024-04-13T22:03:42
> > #[EBILOG:EXITBS:START1 2024-04-13T22:03:42
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [参考远景解决方案](https://bbs.pcbeta.com/viewthread-1961581-1-1.html)
> > 勾选 Config-booter-Quirks-SetupVirtualMap
> > ## Sonoma 14.4验证
> > 无法加载14.4，现目前使用14.2.1正常使用。没有研究为什么，应该是EFI不适配最新Macos导致。
> > ## 总结
> > 此EFI适配铭瑄H610系列应该问题不大。 1、USB端口也无需二次定制（我只用到了四个USB）。 2、蓝牙、Wi-Fi intel AX211 网卡作者更新了最新上游最新kext，现目前驱动正常。 3、2.5G网口正常（我是升级版主板，多出的1G网口未做测试，我也不需要，只需要2.5G网口即可）。
> > 感谢此仓库作者，以及大家的问题反馈和对应的解决方案。
> 
> 我可能近一年没有重新安装，感谢你遇到问题一起分享，后续我会把 14.4 的分享出来，不过最近比较懒，还在测试中。

慢慢等待大佬更新，给大佬点个赞！

**Comment by Arjen10** [comment]
> > > 罗本大佬，请问能否分享一下你的bios设置和efi，研究了两天还是卡EB :( 提前谢谢大佬
> > 
> > 
> > bios 只限制了内存的频率到2667没有使用 3200，efi 晚上分享给你
> 
> 期待罗大佬的分享

https://haishouge.lanzoue.com/ilOyB27yujcf

**Comment by LimeVista** [comment]
> > > > 罗本大佬，请问能否分享一下你的bios设置和efi，研究了两天还是卡EB :( 提前谢谢大佬
> > > 
> > > 
> > > bios 只限制了内存的频率到2667没有使用 3200，efi 晚上分享给你
> > 
> > 
> > 期待罗大佬的分享
> 
> https://haishouge.lanzoue.com/ilOyB27yujcf

一直很懒，虽然早就升级 14.4 了，但没有上传，详情可以可以看这里 https://github.com/LimeVista/Hackintosh-H610-12490F-AX201/discussions/25

**Comment by zywang981** [comment]
> > > > 罗本大佬，请问能否分享一下你的bios设置和efi，研究了两天还是卡EB :( 提前谢谢大佬
> > > 
> > > 
> > > bios 只限制了内存的频率到2667没有使用 3200，efi 晚上分享给你
> > 
> > 
> > 期待罗大佬的分享
> 
> https://haishouge.lanzoue.com/ilOyB27yujcf

您好，很抱歉的请求一下可不可以再分享一下大佬您的EFI，硬盘挂壁了没备份  😢
