### ISSUE TITLE
stucking loading bar

### ISSUE THREAD

**Issue by efecin500** [LimeVista/Hackintosh-H610-12490F-AX201#2]
![16615311414657318643982729624698](https://user-images.githubusercontent.com/98659453/186961975-56f0f53f-6b59-4097-878c-3c0dda75354d.jpg)
i3 12100f
rx6600
Monterey
16gb ram
h610m k d4
i dont have any configuration on config. plist
help

**Comment by LimeVista** [comment]
输出日志给我看看
