### ISSUE TITLE
WiFi 无法打开

### ISSUE THREAD

**Issue by iuiicc** [LimeVista/Hackintosh-H610-12490F-AX201#23]
铭瑄 H610M B660 挑战者

i3 12000F

5500XT

BCM94360CD

虽然配置不对，但是能用，然后安装后， wifi 无法打开

请问大佬，我应该怎么排查或者修改🥹

**Comment by LimeVista** [comment]
把我的驱动删除就行，我是针对 Intel 网卡的驱动，删除这个 `itlwm` 这个驱动，打上博通的补丁

**Comment by LimeVista** [comment]
蓝牙驱动也要删除，分别是 `IntelBluetoothFirmware.kext` 和 `IntelBTPatcher.kext`

**Comment by LimeVista** [comment]
`config.plist` 记得要编辑一下
