### ISSUE TITLE
H610I - 12400F - 6600XT - AX200 可以用

### ISSUE THREAD

**Issue by 1103409364** [LimeVista/Hackintosh-H610-12490F-AX201#3]
- 如果 主板开启了 Resize Bar Support，需要把 booter 里面的 ResizeAppleGpuBars从 -1 改成 0。否则卡进度条

- 在 **windows** 下**没有**电流声，切换到 macOS 下有电流声，可能是显卡调度问题。没找到好的解决办法。电源是海鲜市场的银欣SFX 500W。也可能是电源垃圾

- [无核显开启随航](https://www.bilibili.com/video/BV1uX4y1u73k) 无核显貌似可以开启有线随航

**Comment by LimeVista** [comment]
显卡的问题，我可能无能为力。目前我这边没有发现电流声问题。

**Comment by LimeVista** [comment]
1.  无核显随航的方案我尝试了下，机型（SMBIOS）必须修改，而且不是很稳定。
2. 尝试了下现有的思路，均没有很好的方式
3. 参考：[https://github.com/AMD-OSX/bugtracker/issues/1](https://github.com/AMD-OSX/bugtracker/issues/1)
