### ISSUE TITLE
主板BIOS版本

### ISSUE THREAD

**Issue by SLi-Man** [LimeVista/Hackintosh-H610-12490F-AX201#4]
主板刚买回来BIOS版本是最新的E1.4G，但是默认锁了CFG Lock，安装一直卡在EB，试过了更改OC config.plist里的IgnoreInvalidFlexRatio、AppleXcpmCfgLock、AppleCpuPmCfgLock、SetupVirtualMap都没有效果，想问下各位你们的BIOS版本是多少

**Comment by HaidyCao** [comment]
@SLi-Man 大佬，E1.4G的bios可以跑起来了么

**Comment by SLi-Man** [comment]
> @SLi-Man 大佬，E1.4G的bios可以跑起来了么

我后来是刷了E1.3G和E1.2G的BIOS都不行的情况下，自己从头配置的OC安装成功了，目前遇到的问题就是ALC897板载声卡在黑苹果上检测不到

**Comment by LimeVista** [comment]
我目前是 E1.1G 版本 BIOS @SLi-Man

**Comment by HaidyCao** [comment]
> 

如果你是1.4的话，能共享下配置不😭我现在用的1.3是可以的但是内存频率只能2966

**Comment by HaidyCao** [comment]
@SLi-Man

**Comment by SLi-Man** [comment]
> 如果你是1.4的话，能共享下配置不😭我现在用的1.3是可以的但是内存频率只能2966

@HaidyCao 我现在用的是[[LimeVista](https://github.com/LimeVista)](https://github.com/LimeVista/Hackintosh-H610-12490F-AX201)的这个EFI，主要是成功解决了我的板载声卡驱动问题，目前还在完善中。

BIOS我现在用的是E1.2G，感觉你的内存频率跟BIOS版本应该没关系，我E1.2G在BIOS中开启XMP频率稳定3200

**Comment by HaidyCao** [comment]
@SLi-Man 目前除了内存频率上不去其他都挺好 刷了1.4的确可以上3200，不过问题不大

**Comment by yangzhennupt** [comment]
> @SLi-Man 目前除了内存频率上不去其他都挺好 刷了1.4的确可以上3200，不过问题不大

最新EFI 1.4版本可以直接用吗
