### ISSUE TITLE
Hackintool显示CPU架构是问号

### ISSUE THREAD

**Issue by xuconnery** [LimeVista/Hackintosh-H610-12490F-AX201#6]
感谢大佬分享自己的efi，本人是12400f+铭瑄h610m，用大佬的efi更换网卡驱动后似乎一切正常，只是Hackintool显示CPU架构是问号，不知有什么问题，又要如何修正？

**Comment by LimeVista** [comment]
Hackintool CPU架构 显示三个问号吧，因为仿冒的是 10代 CPU，并且无法驱动核显。
只要睿频、功耗是正常的，就没啥问题。

**Comment by xuconnery** [comment]
Okkk
