### ISSUE TITLE
请问使用这个配置还需要定制 USB 吗？

### ISSUE THREAD

**Issue by hkchenhao** [LimeVista/Hackintosh-H610-12490F-AX201#7]
请问各位大佬使用这个配置还需要定制 USB 吗？还是说直接用就可以了，我这边的配置是 H610I 12100F AX201 RX6600？是不是可以直接用

**Comment by xuconnery** [comment]
可以的，我的h610m都是直接用

**Comment by LimeVista** [comment]
如果是铭瑄 H610i 那块主板，是不用的。

**Comment by jackyiero** [comment]
我的配置是12100f+铭瑄挑战者h610m+rx580+博通无线网卡，装好后没有声音，休眠也不正常

**Comment by LimeVista** [comment]
> 我的配置是12100f+铭瑄挑战者h610m+rx580+博通无线网卡，装好后没有声音，休眠也不正常
挑战者不太清楚，我是铭瑄 H610 ITX，已经定制好了

**Comment by LimeVista** [comment]
挑战者不太清楚，我是铭瑄 H610 ITX，已经定制好了
