### ISSUE TITLE
大家是否遇到系统偏好设置里的项卡顿问题

### ISSUE THREAD

**Issue by xuconnery** [LimeVista/Hackintosh-H610-12490F-AX201#8]
已经遇到过好几次了，系统偏好设置里，切换到某些设置项时，会卡顿、

并不是系统层面的卡顿，因此此时其他程序都没问题，唯独系统偏好设置的这个会一直卡住不动。

比如：

1、安装应用时，要进到安全性与隐私，点击“已阻止xxx，因为来源身份不明的开发者”的仍要打开，就卡住不动了。
2、在键盘偏好设置里，切换到设置输入法的快捷键时，也会卡住不动。

但上述问题并不是每次都会复现。很奇怪。

**Comment by LimeVista** [comment]
我小概率发生过，尚不明确是啥问题。

**Comment by xuconnery** [comment]
额，我是从来没遇到过才提出来。一台是白果，一台是9600k+b360m黑果，都没碰到过
