### ISSUE TITLE
进入EFI选择安装Ventura后卡白苹果logo

### ISSUE THREAD

**Issue by ValerioL29** [LimeVista/Hackintosh-H610-12490F-AX201#9]
不知道是不是镜像的问题，我进入OC的引导后选择开始安装Ventura项后就会卡在白苹果Logo，并且没有进度条。（请问可以分享一下作者您使用的镜像么？）

**Comment by LimeVista** [comment]
-v 模式查看卡住日志

**Comment by ValerioL29** [comment]
> -v 模式查看卡住日志

解决了：BIOS 1.4版本无法正常进oc跑代码，降级到1.3后并打开-v即可正常跑代码进安装，谢谢作者
